"""add resume tables

Revision ID: 2ad2439d3f02
Revises: 4eb77560026d
Create Date: 2026-07-14 18:26:08.317069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad2439d3f02'
down_revision: Union[str, Sequence[str], None] = '4eb77560026d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='简历标题'),
    sa.Column('file_type', sa.String(length=10), nullable=False, comment='文件类型 (pdf/doc/docx)'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='提取的纯文本'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/processing/completed/failed'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('resume_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='简历ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='块序号（从0开始）'),
    sa.Column('content', sa.Text(), nullable=False, comment='块内容'),
    sa.Column('char_count', sa.Integer(), nullable=False, comment='字符数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_chunks_resume_id'), 'resume_chunks', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_chunks_resume_id'), table_name='resume_chunks')
    op.drop_table('resume_chunks')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
