"""add_last_used_at_to_refresh_tokens

Revision ID: 4eb77560026d
Revises: ba0db57b93fe
Create Date: 2026-07-14 14:07:38.665504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb77560026d'
down_revision: Union[str, Sequence[str], None] = 'ba0db57b93fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    # ### end Alembic commands ###
