"""add structured_data to resumes

Revision ID: 71d6caa7da26
Revises: 2ad2439d3f02
Create Date: 2026-07-14 19:56:02.124596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d6caa7da26'
down_revision: Union[str, Sequence[str], None] = '2ad2439d3f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('structured_data', sa.JSON(), nullable=True, comment='结构化解析结果（规则提取的基础信息、教育、工作、项目、技能）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'structured_data')
    # ### end Alembic commands ###
