"""add job recommendation tasks

Revision ID: 7314b9ddef4a
Revises: 976057e879ed
Create Date: 2026-07-14 23:09:47.807588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7314b9ddef4a'
down_revision: Union[str, Sequence[str], None] = '976057e879ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_platform_login_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='关联简历ID'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='招聘平台'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='waiting_login/logged_in/expired/failed'),
    sa.Column('storage_state_ref', sa.String(length=500), nullable=True, comment='服务端私有登录态文件引用'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='脱敏错误信息'),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_platform_login_sessions_expires_at'), 'job_platform_login_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_job_platform_login_sessions_user_id'), 'job_platform_login_sessions', ['user_id'], unique=False)
    op.create_table('job_recommend_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('resume_id', sa.BigInteger(), nullable=False, comment='简历ID'),
    sa.Column('login_session_id', sa.String(length=36), nullable=True, comment='登录会话ID'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='招聘平台'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/crawling/matching/success/failed/need_login'),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('extracted_skills', sa.JSON(), nullable=True),
    sa.Column('search_keywords', sa.JSON(), nullable=True),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.Column('total_matched', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_session_id'], ['job_platform_login_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_recommend_tasks_resume_id'), 'job_recommend_tasks', ['resume_id'], unique=False)
    op.create_index(op.f('ix_job_recommend_tasks_user_id'), 'job_recommend_tasks', ['user_id'], unique=False)
    op.create_table('job_recommend_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('matched_skill_count', sa.Integer(), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['job_recommend_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'job_id', name='uq_recommend_task_job')
    )
    op.create_index(op.f('ix_job_recommend_results_task_id'), 'job_recommend_results', ['task_id'], unique=False)
    op.create_index(op.f('ix_job_recommend_results_user_id'), 'job_recommend_results', ['user_id'], unique=False)
    op.drop_column('job_applications', 'applied_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('applied_at', mysql.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_job_recommend_results_user_id'), table_name='job_recommend_results')
    op.drop_index(op.f('ix_job_recommend_results_task_id'), table_name='job_recommend_results')
    op.drop_table('job_recommend_results')
    op.drop_index(op.f('ix_job_recommend_tasks_user_id'), table_name='job_recommend_tasks')
    op.drop_index(op.f('ix_job_recommend_tasks_resume_id'), table_name='job_recommend_tasks')
    op.drop_table('job_recommend_tasks')
    op.drop_index(op.f('ix_job_platform_login_sessions_user_id'), table_name='job_platform_login_sessions')
    op.drop_index(op.f('ix_job_platform_login_sessions_expires_at'), table_name='job_platform_login_sessions')
    op.drop_table('job_platform_login_sessions')
    # ### end Alembic commands ###
